package ru.otus.otuskotlin.cleaningaggregator.common.stubs

enum class ClagStubs {
    NONE,
    SUCCESS,
    BAD_ID,
    BAD_CLEANING_TYPE,
    BAD_SCHEDULED_DATE,
    BAD_DESCRIPTION,
    BAD_SPECIAL_REQUIREMENTS,
    BAD_ADDRESS,
    BAD_SEARCH_STRING,
    ORDER_NOT_FOUND,
    ORDER_ALREADY_PUBLISHED,
    ORDER_ALREADY_RESPONDED,
    ORDER_ALREADY_DELETED,
    NOT_ENOUGH_PERMISSIONS,
    BAD_LOCK_VERSION,
    DATABASE_ERROR
}
