openapi: '3.0.3'
info:
  title: Cleaning Aggregator log models
  description: Log models for logging services of Cleaning Aggregator
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths: {}

components:
  schemas:
    CommonLogModel:
      title: Общая модель лога
      description: Общая модель лога для всех микросервисов системы
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        source:
          type: string
        order:
          $ref: '#/components/schemas/ClagOrderLogModel'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogModel'

    ClagOrderLogModel:
      title: Модель лога для микросервиса `order`
      type: object
      properties:
        requestId:
          type: string
        operation:
          type: string
          enum:
            - create
            - read
            - update
            - delete
            - publish
            - respond
            - search
            - init
            - finish
        requestOrder:
          $ref: '#/components/schemas/OrderLog'
        requestFilter:
          $ref: '#/components/schemas/OrderFilterLog'
        responseOrder:
          $ref: '#/components/schemas/OrderLog'
        responseOrders:
          type: array
          items:
            $ref: '#/components/schemas/OrderLog'

    OrderLog:
      title: Модель лога для объекта `order`
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        cleaningType:
          type: string
        sheduledFor:
          type: string
        specialRequirements:
          type: string
        address:
          type: object
          properties:
            city:
              type: string
            street:
              type: string
            house:
              type: string
            apartment:
              type: string
            floor:
              type: integer
            entranceNumber:
              type: string
        cost:
          type: object
          properties:
            amount:
              type: string
            currency:
              type: string
        customerId:
          type: string
        executorId:
          type: string
        status:
          type: string
        metadata:
          type: object
          properties:
            createdAt:
              type: string
            updatedAt:
              type: string
            publishedAt:
              type: string
            respondedAt:
              type: string
            deletedAt:
              type: string
        permissions:
          type: array
          uniqueItems: true
          items:
            type: string

    OrderFilterLog:
      title: Модель лога фильтра
      properties:
        cleaningType:
          type: string
        dateRange:
          type: object
          properties:
            start:
              type: string
            end:
              type: string
        locationRange:
          type: object
          properties:
            city:
              type: string
            street:
              type: string
            house:
              type: string
            radius:
              type: number
            
    ErrorLogModel:
      title: Модель лога для ошибки
      type: object
      properties:
        message:
          type: string
        field:
          type: string
        code:
          type: string
        level:
          type: string
